import java.util.Random;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Michael
 */
public class checkin extends javax.swing.JFrame {
    public Connection cons;
    public Statement stat;
    int value;
    public checkin() {
        initComponents();
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            cons = DriverManager.getConnection("jdbc:mysql://localhost:3306/crud","root",""); //connection
            stat = cons.createStatement();
        
        }
        catch (Exception E) {
            JOptionPane.showMessageDialog(null,"Program Can't Connect To Database!");
            System.exit(0);
        }
         
         kodebook.setEditable(false);
         name.setEditable(false);
         alamat.setEditable(false);
         nohp.setEditable(false);
         tipekamar.setEditable(false);
         tglcheck.setEditable(false);
         lamainap.setEditable(false);
         harga.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        checkkodebooking = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        kodebook = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        nohp = new javax.swing.JTextField();
        tipekamar = new javax.swing.JTextField();
        lamainap = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        info = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        warning = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tglcheck = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Masukkan Kode Booking Yang Didapat  : ");

        checkkodebooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkkodebookingActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("KODE BOOKING :");

        jLabel3.setText("NAMA : ");

        jLabel4.setText("ALAMAT : ");

        jLabel5.setText("NOMOR HP :");

        jLabel6.setText("TIPE KAMAR :");

        jLabel7.setText("LAMA INAP :");

        jLabel8.setText("HARGA : ");

        tipekamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipekamarActionPerformed(evt);
            }
        });

        info.setBackground(new java.awt.Color(0, 0, 0));
        info.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        info.setForeground(new java.awt.Color(255, 0, 0));

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("NB : Mohon Dicek Kembali Apakah Data Yang Muncul Sudah Sesuai / Belum");

        jLabel10.setText("Rp.");

        jLabel11.setText("HARI");

        jButton2.setText("Check In");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        warning.setForeground(new java.awt.Color(204, 51, 0));
        warning.setText("        ");

        jLabel12.setText("TGL CHECK IN :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(warning)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(checkkodebooking, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamat)
                    .addComponent(name)
                    .addComponent(kodebook)
                    .addComponent(nohp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tipekamar)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lamainap, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tglcheck))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkkodebooking, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kodebook, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nohp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tipekamar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tglcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lamainap, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(37, 37, 37)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warning)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkkodebookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkkodebookingActionPerformed
        
    }//GEN-LAST:event_checkkodebookingActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
           String db = "select *from reservation where KodeBooking = '" +checkkodebooking.getText() + "'";
           
           ResultSet result = stat.executeQuery(db);
           
           if(result.next()){
               
               info.setText("Data Ditemukan!");
             
                   String kode = result.getString("KodeBooking");
                   kodebook.setText(kode);
                   
                   String getnama = result.getString("Nama");
                   name.setText(getnama);
                   
                   String address = result.getString("Alamat");
                   alamat.setText(address);
                   
                   String number = result.getString("No HP");
                   nohp.setText(number);
                   
                   String Type = result.getString("TipeKamar");
                   tipekamar.setText(Type);
                   
                   String tgl = result.getString("TglCheckIn");
                   tglcheck.setText(tgl);
                   
                   String lama = result.getString("LamaInap");
                   lamainap.setText(lama);
                   
                   String price = result.getString("Harga");
                   harga.setText(price);

           }
           
           else{
               info.setText("Data Tidak Ditemukan!");
               kodebook.setText(null);
               name.setText(null);
               alamat.setText(null);
               nohp.setText(null);
               tipekamar.setText(null);
               lamainap.setText(null);
               harga.setText(null);
               
           }
       
       }
       
       catch(Exception E){
           JOptionPane.showMessageDialog(null, "Terjadi Sebuah Kesalahan!");
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(kodebook.getText().trim().isEmpty() && name.getText().trim().isEmpty() && alamat.getText().trim().isEmpty() && nohp.getText().trim().isEmpty()
              && tipekamar.getText().trim().isEmpty() && lamainap.getText().trim().isEmpty() && harga.getText().trim().isEmpty()){
            warning.setText("Data Tidak Ditemukan! Mohon Masukkan Kode Booking Yang Sesuai!");
            value = -1;
        }
        
        else{
            value = 1;
        }
        
        if (value > 0){
        int decision = JOptionPane.showConfirmDialog(null, "Apakah data yang ditampilkan sudah sesuai ?","WARNING!" ,JOptionPane.YES_NO_OPTION , JOptionPane.QUESTION_MESSAGE);
        
        if (decision == JOptionPane.YES_OPTION){

                Random rand = new Random();
                int RandomNumb = rand.nextInt(10);
                int kamar;
                int pembayaran;
                int intharga;
                int kembalian;
                String room =tipekamar.getText();

            try{
                String data = "insert into checkin values (?,?,?,?,?,?,?,?,?,?,?);";
            if (room.equals("Standard")){
                kamar = 100+RandomNumb;
                String dbase = "select *from " +room + " where NoKamar = '" + String.valueOf(kamar) + "'";
               
                ResultSet hasil = stat.executeQuery(dbase);
                
                if(hasil.next()){
                String nokamar= hasil.getString("NoKamar");
                String lantai = hasil.getString("LantaiKamar");
                
                do{
                 pembayaran = Integer.parseInt(JOptionPane.showInputDialog("Harga Kamar : Rp. " +harga.getText() + "\nMasukkan Jumlah Uang : "));
                
                intharga = Integer.valueOf(harga.getText());
            
                if(pembayaran >= intharga){
                    kembalian = pembayaran - intharga;
                    JOptionPane.showMessageDialog(null,"Pembayaran Berhasil! Jumlah Kembalian : Rp. " +kembalian);
                    JOptionPane.showMessageDialog(null,"Selamat Anda BERHASIL Check In!" + " Kamar Anda Ada Di Lantai "+lantai + "\nDengan Nomor Kamar : " +nokamar);
                     
                    PreparedStatement statement = cons.prepareStatement(data);
                    
                    statement.setString(1, kodebook.getText());
                    statement.setString(2, name.getText());
                    statement.setString(3, alamat.getText());
                    statement.setString(4, nohp.getText());
                    statement.setString(5, tipekamar.getText());
                    statement.setString(6, nokamar);
                    statement.setString(7, lamainap.getText());
                    statement.setString(8, tglcheck.getText());
                    statement.setString(9, harga.getText());
                    statement.setString(10, String.valueOf(pembayaran));
                    statement.setString(11, String.valueOf(kembalian));
                    
                    statement.executeUpdate();
                    home home = new home();
                    home.setVisible(true);
                    this.dispose();
                }
                
                else{
                    JOptionPane.showMessageDialog(null, "Pembayaran Kurang! Masukkan Jumlah Uang Kembali!");   
                  }
                }while(pembayaran < intharga);           
              }
            }
            
            else if (room.equals("Family")){
                kamar = 200+RandomNumb;
                String dbase = "select *from " +room + " where NoKamar = '" + String.valueOf(kamar) + "'";
                ResultSet hasil = stat.executeQuery(dbase);
                
                if(hasil.next()){
                String nokamar= hasil.getString("NoKamar");
                String lantai = hasil.getString("LantaiKamar");
                do{
                 pembayaran = Integer.parseInt(JOptionPane.showInputDialog("Harga Kamar : Rp. " +harga.getText() + "\nMasukkan Jumlah Uang : "));
                
                intharga = Integer.valueOf(harga.getText());
            
                if(pembayaran >= intharga){
                    kembalian = pembayaran - intharga;
                    JOptionPane.showMessageDialog(null,"Pembayaran Berhasil! Jumlah Kembalian : Rp. " +kembalian);
                    JOptionPane.showMessageDialog(null,"Selamat Anda BERHASIL Check In!" + " Kamar Anda Ada Di Lantai "+lantai + "\nDengan Nomor Kamar : " +nokamar);
                    
                    PreparedStatement statement = cons.prepareStatement(data);
                    
                    statement.setString(1, kodebook.getText());
                    statement.setString(2, name.getText());
                    statement.setString(3, alamat.getText());
                    statement.setString(4, nohp.getText());
                    statement.setString(5, tipekamar.getText());
                    statement.setString(6, nokamar);
                    statement.setString(7, lamainap.getText());
                    statement.setString(8, tglcheck.getText());
                    statement.setString(9, harga.getText());
                    statement.setString(10, String.valueOf(pembayaran));
                    statement.setString(11, String.valueOf(kembalian));
                    
                    statement.executeUpdate();
                    home home = new home();
                    home.setVisible(true);
                    this.dispose();
                }
                
                else{
                    JOptionPane.showMessageDialog(null, "Pembayaran Kurang! Masukkan Jumlah Uang Kembali!");   
                  }
                }while(pembayaran < intharga);
              }
            }
            
            else if (room.equals("Deluxe")){
                kamar = 300+RandomNumb;
                String dbase = "select *from " +room + " where NoKamar = '" + String.valueOf(kamar) + "'";
                ResultSet hasil = stat.executeQuery(dbase);
                
                if(hasil.next()){
                String nokamar= hasil.getString("NoKamar");
                String lantai = hasil.getString("LantaiKamar");

              do{
                 pembayaran = Integer.parseInt(JOptionPane.showInputDialog("Harga Kamar : Rp. " +harga.getText() + "\nMasukkan Jumlah Uang : "));
                
                intharga = Integer.valueOf(harga.getText());
            
                if(pembayaran >= intharga){
                    kembalian = pembayaran - intharga;
                    JOptionPane.showMessageDialog(null,"Pembayaran Berhasil! Jumlah Kembalian : Rp. " +kembalian);
                    JOptionPane.showMessageDialog(null,"Selamat Anda BERHASIL Check In!" + " Kamar Anda Ada Di Lantai "+lantai + "\nDengan Nomor Kamar : " +nokamar);
                    
                    PreparedStatement statement = cons.prepareStatement(data);
                    
                    statement.setString(1, kodebook.getText());
                    statement.setString(2, name.getText());
                    statement.setString(3, alamat.getText());
                    statement.setString(4, nohp.getText());
                    statement.setString(5, tipekamar.getText());
                    statement.setString(6, nokamar);
                    statement.setString(7, lamainap.getText());
                    statement.setString(8, tglcheck.getText());
                    statement.setString(9, harga.getText());
                    statement.setString(10, String.valueOf(pembayaran));
                    statement.setString(11, String.valueOf(kembalian));
                    
                    statement.executeUpdate();
                    home home = new home();
                    home.setVisible(true);
                    this.dispose();
                }
                
                else{
                    JOptionPane.showMessageDialog(null, "Pembayaran Kurang! Masukkan Jumlah Uang Kembali!");   
                  }
                }while(pembayaran < intharga);
              }
            }
            
            else if (room.equals("Suite")){
                kamar = 400+RandomNumb;
                String dbase = "select *from " +room + " where NoKamar = '" + String.valueOf(kamar) + "'";
                ResultSet hasil = stat.executeQuery(dbase);
                
                if(hasil.next()){
                String nokamar= hasil.getString("NoKamar");
                String lantai = hasil.getString("LantaiKamar");
                do{
                 pembayaran = Integer.parseInt(JOptionPane.showInputDialog("Harga Kamar : Rp. " +harga.getText() + "\nMasukkan Jumlah Uang : "));
                
                intharga = Integer.valueOf(harga.getText());
            
                if(pembayaran >= intharga){
                    kembalian = pembayaran - intharga;
                    JOptionPane.showMessageDialog(null,"Pembayaran Berhasil! Jumlah Kembalian : Rp. " +kembalian);
                    JOptionPane.showMessageDialog(null,"Selamat Anda BERHASIL Check In!" + " Kamar Anda Ada Di Lantai "+lantai + "\nDengan Nomor Kamar : " +nokamar);
                    
                    PreparedStatement statement = cons.prepareStatement(data);
                    
                    statement.setString(1, kodebook.getText());
                    statement.setString(2, name.getText());
                    statement.setString(3, alamat.getText());
                    statement.setString(4, nohp.getText());
                    statement.setString(5, tipekamar.getText());
                    statement.setString(6, nokamar);
                    statement.setString(7, lamainap.getText());
                    statement.setString(8, tglcheck.getText());
                    statement.setString(9, harga.getText());
                    statement.setString(10, String.valueOf(pembayaran));
                    statement.setString(11, String.valueOf(kembalian));
                    
                    statement.executeUpdate();
                    home home = new home();
                    home.setVisible(true);
                    this.dispose();
                }
                
                else{
                    JOptionPane.showMessageDialog(null, "Pembayaran Kurang! Masukkan Jumlah Uang Kembali!");   
                  }
                }while(pembayaran < intharga);
              }
            }

         }
            
            catch (Exception E){
                JOptionPane.showMessageDialog(null, "Mohon Maaf! Kode Booking Yang Dimasukkan Sudah Pernah Dilakukan Check In!");
            }
          }
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       home home = new home();
       home.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tipekamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipekamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipekamarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField checkkodebooking;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kodebook;
    private javax.swing.JTextField lamainap;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nohp;
    private javax.swing.JTextField tglcheck;
    private javax.swing.JTextField tipekamar;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
